### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by edahlseng** [FutureSharks/tf-kops-cluster#17]
To help newcomers get started with this module, I think it could be valuable to add some more detailed documentation, particularly about the different variables that can be specified. If you think this could be valuable, I'm happy to take a first stab at drafting some things up!

**Comment by FutureSharks** [comment]
For sure! I included comments in the [variables.tf](https://github.com/FutureSharks/tf-kops-cluster/blob/master/module/variables.tf) but perhaps details in the README.md file would be better?

**Comment by FutureSharks** [comment]
I'm gonna close this now. You can open a PR to add more documentation.
