### ISSUE TITLE
Master nodes OutOfService

### ISSUE THREAD

**Issue by edahlseng** [FutureSharks/tf-kops-cluster#18]
I'm not sure yet what the source of this issue is, so putting it here until further information is discovered.

When running up a cluster using this module, all master nodes are marked as OutOfService by the load balancer because they are failing health checks. Is this something that you've seen before, maybe an easy fix?

**Comment by FutureSharks** [comment]
We can troubleshoot this but it's important that if you've deviated from what's in the [example](https://github.com/FutureSharks/tf-kops-cluster/tree/master/example) that you know what you are doing.

What domain are you using? Is it real? Is it associated with your VPC? Can your nodes resolve each others hostnames and that records in your Route53 domain?

**Comment by FutureSharks** [comment]
I have just merged large PR that rewrites a lot of logic and switches to kops 1.8. Perhaps retest again using the example and the latest changes in master?

**Comment by edahlseng** [comment]
Sounds good. Also, I discovered last night that if I didn't specify `private_subnet_ids`, then everything worked successfully. It's possible that there was an error in the routing configuration for my private subnets. Though I did have elastic beanstalk applications successfully running in those subnets, which suggests otherwise.

Will retest (possibly in a couple days) with the latest and report back with any findings.

**Comment by FutureSharks** [comment]
OK. Bear in mind that in a private subnet that the default route needs to go to a route table where the default route is to a NAT gateway, which is connected to a public subnet. Like this:
`private subnet -> private route table 1 -> NAT gateway > public subnet > internet gateway`

If you put a k8s node in a completely private subnet (no route to the internet at all) then nothing will work.

If your elastic beanstalk nodes are behind an ELB but in a completely private subnet (no route to the internet at all) this could still possibly work as requests from the ELB to an instance will be answered but the instance won't be able to reach the internet.

**Comment by FutureSharks** [comment]
I'm gonna close this now. Feel free to reopen it if it's still an issue.
